modLoader="javafml"
loaderVersion="[36,)"
license="Not specified"

[[mods]]
modId="fallout_wastelands"
version="Beta 0.5.8"
displayName="Fallout Wastelands"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
logoFile="logo.png"
authors="Vaedak,Mechanist1108,FoxysYT,Mcreator"
description='''
A Fallout game serie mod for minecraft , with vault-craft we assure you a calm and bright future !
'''

[[dependencies.fallout_wastelands]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5]"
    ordering="NONE"
    side="BOTH"




